### ISSUE TITLE
Create support for Craft 3

### ISSUE THREAD

**Issue by askogrand** [onedesign/craft-fastly#4]
Can the plugin be updated to support the soon to be released Craft 3?

https://github.com/craftcms/docs/blob/v3/en/coding-guidelines.md

**Comment by cmalven** [comment]
Hi @askogrand! This plugin hasn't been updated in awhile, and at this point I'd probably recommend you use https://github.com/ostark/upper which is a similar plugin supporting a variety of CDNs in addition to Fastly, and supports Craft 3.
